# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-20 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qrious', '0005_player_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='answers_given',
            field=models.CharField(default='000000', max_length=100),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question_no',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
