# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-20 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qrious', '0006_auto_20170320_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='question_img',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
