# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-21 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qrious', '0008_auto_20170321_0052'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='questions_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
