# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-21 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qrious', '0010_remove_questions_questions_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
